// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Objectbay.Vacation.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231124083741_Seed_update")]
    partial class Seed_update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Objectbay.Vacation.WebApi.DbModels.VacationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VacationItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fb362d5-18c3-45de-813e-6147adbc3d9a"),
                            Category = 0,
                            Name = "Bikini"
                        },
                        new
                        {
                            Id = new Guid("c37f373d-6869-48a2-a8c0-2e3b2626da6a"),
                            Category = 3,
                            Name = "Sonnencreme"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
